$(".about_me").click(function(event){
    $(".main_page").toggle()
})
$(".coding_works").click(function(event){
    $(".portfolio").toggle()
})
$(".written_works").click(function(event){
    $(".writing_samples").toggle()
})